export const CHARS = [
  {
    id: 'dennis', name: 'Dennis of House Reynolds',
    cls: 'Sorcerer · Wild Magic',
    tag: '"My power is deliberate. The explosions are also deliberate. Everything is deliberate."',
    lore: 'CHA 18. His magic is chaotic and uncontrolled. He insists it is not. Wild Magic Surges happen constantly. He has a different explanation each time. Nobody is buying it.',
    hp: 32, ac: 13, speed: 30, prof: 3,
    stats: { STR:8, DEX:14, CON:12, INT:12, WIS:10, CHA:18 },
    imgKey: 'dennis', accentColor: '#c8a820',
  },
  {
    id: 'mac', name: 'Mac the Unbroken',
    cls: 'Paladin · Oath of Conquest',
    tag: '"I have cultivated a very specific set of skills. I\'m still figuring out what they are."',
    lore: 'Sworn an oath he does not understand. Calls his Divine Smite karate. STR 16, WIS 6. Aura of Conquest affects the party more than enemies. Carries a weapon he swings incorrectly.',
    hp: 52, ac: 18, speed: 30, prof: 3,
    stats: { STR:16, DEX:8, CON:14, INT:8, WIS:6, CHA:12 },
    imgKey: 'mac', accentColor: '#a03010',
  },
  {
    id: 'charlie', name: 'Charlie of the Below',
    cls: 'Druid · Circle of Spores',
    tag: '"I figured it out. I figured all of it out. None of you listened."',
    lore: 'Illiterate. INT 4, WIS 18. Permanent Speak with Animals. Knows every tunnel, every rat, every secret passage. The most competent member of the party. They never listen.',
    hp: 44, ac: 13, speed: 30, prof: 3,
    stats: { STR:10, DEX:12, CON:14, INT:4, WIS:18, CHA:8 },
    imgKey: 'charlie', accentColor: '#4a8830',
  },
  {
    id: 'dee', name: 'Dee the Unbroken Bird',
    cls: 'Bard · College of Eloquence',
    tag: '"I am a classically trained enchantress and I will not be spoken to like this."',
    lore: 'Performance maxed. Bardic Inspiration rarely lands. Her spells technically work but the delivery undermines them. Insists her Inspiration dice are d10. They are d4.',
    hp: 36, ac: 13, speed: 30, prof: 3,
    stats: { STR:8, DEX:13, CON:10, INT:12, WIS:10, CHA:16 },
    imgKey: 'dee', accentColor: '#7050b0',
  },
  {
    id: 'frank', name: 'Frank the Undying',
    cls: 'Barbarian · Path of the Beast',
    tag: '"I\'ve gone feral before. This is just more formal."',
    lore: 'CON 18. STR 16. WIS 3. Rage is his baseline state. The Beast features were always there — the claws, the bite. Nobody questioned it until now. No armor. Never armor.',
    hp: 65, ac: 13, speed: 30, prof: 3,
    stats: { STR:16, DEX:8, CON:18, INT:6, WIS:3, CHA:10 },
    imgKey: 'frank', accentColor: '#806020',
  },
];

export const IDENTITY = {
  dennis: {
    doesLabel: 'HE DOES:',
    does: 'Bends reality with wild, unpredictable magic. Charms enemies, throws chaos into every fight, and occasionally explodes something by accident.',
    forPlayer: 'The player who wants to feel powerful and unhinged. You\'re not here to follow the plan — you are the plan going wrong in the best possible way.',
  },
  mac: {
    doesLabel: 'HE DOES:',
    does: 'Charges into battle in heavy armor, smites enemies with holy power, and bends his sworn oath to justify whatever he was going to do anyway.',
    forPlayer: 'The player who wants to be the muscle with a god complex. You hit hard, you look righteous doing it, and you\'re pretty sure you\'re the main character.',
  },
  charlie: {
    doesLabel: 'THEY DO:',
    does: 'Controls the battlefield with nature magic, transforms into animals, and communicates with creatures no one else can understand.',
    forPlayer: 'The player who wants to be quietly indispensable. You won\'t always get the credit, but nothing works without you — and you know things the others don\'t.',
  },
  dee: {
    doesLabel: 'SHE DOES:',
    does: 'Inspires allies, manipulates enemies with words, and casts spells while maintaining an air of wounded dignity.',
    forPlayer: 'The player who wants to be the smartest person in the room and make sure everyone knows it. You support the party — on your terms, with commentary.',
  },
  frank: {
    doesLabel: 'HE DOES:',
    does: 'Rages into combat, shrugs off damage that would kill anyone else, and occasionally transforms into something that should not be possible.',
    forPlayer: 'The player who wants to cause problems and survive them. No plan, no fear, no explanation. You\'re just built different.',
  },
};

export const PRIMARY_STAT = { dennis:'cha', mac:'str', charlie:'wis', dee:'cha', frank:'str' };

export const SHEETS = {
  dennis: {
    level1: {
      class:'Sorcerer', subclass:null,
      hp:7, ac:11, speed:30,
      str:8, dex:12, con:14, int:10, wis:10, cha:16,
      skills:{ Acrobatics:1, Deception:3, Insight:0, Intimidation:3, Perception:0 },
      cantrips:['Mage Hand','Prestidigitation','Ray of Frost','Spark of Life'],
      spells_1:['Magic Missile','Shield'],
      spells_2:[],
      features:['Wild Magic Surge (dormant)'],
      equipment:['Quarterstaff','Dagger','Leather Armor','Spell Component Pouch'],
    },
    level5: {
      class:'Wild Magic Sorcerer', subclass:'Wild Magic',
      hp:31, ac:13, speed:30,
      str:8, dex:14, con:16, int:10, wis:12, cha:18,
      skills:{ Acrobatics:2, Deception:4, Insight:1, Intimidation:4, Perception:1 },
      cantrips:['Mage Hand','Prestidigitation','Ray of Frost','Spark of Life'],
      spells_1:['Magic Missile','Shield','Feather Fall','Charm Person'],
      spells_2:['Scorching Ray','Invisibility','Suggestion'],
      features:['Wild Magic Surge','Tides of Chaos','Bend Luck'],
      equipment:['Quarterstaff','Dagger','Leather Armor','Spell Component Pouch','Wild Magic Surge Tokens'],
    },
  },
  mac: {
    level1: {
      class:'Paladin', subclass:'Oath of Conquest',
      hp:12, ac:18, speed:30,
      str:16, dex:12, con:14, int:10, wis:13, cha:15,
      skills:{ Acrobatics:1, Athletics:5, Intimidation:2, Perception:2, Persuasion:2 },
      cantrips:['Light','Thaumaturgy'],
      spells_1:['Bless','Cure Wounds'],
      spells_2:[],
      features:["Divine Sense","Lay on Hands","Conqueror's Strike"],
      equipment:['Longsword','Shield','Plate Armor','Holy Symbol','Javelin'],
    },
    level5: {
      class:'Paladin', subclass:'Oath of Conquest',
      hp:44, ac:20, speed:30,
      str:19, dex:14, con:16, int:10, wis:15, cha:17,
      skills:{ Acrobatics:2, Athletics:7, Intimidation:5, Perception:4, Persuasion:5 },
      cantrips:['Light','Thaumaturgy'],
      spells_1:['Bless','Cure Wounds','Shield of Faith','Protection from Evil and Good'],
      spells_2:['Aid','Brand of Justice'],
      features:['Divine Smite',"Conqueror's Strike",'Aura of Conquest','Extra Attack'],
      equipment:['Longsword','Shield','Plate Armor','Holy Symbol','Javelin'],
    },
  },
  charlie: {
    level1: {
      class:'Druid', subclass:'Circle of Spores',
      hp:9, ac:11, speed:30,
      str:12, dex:14, con:16, int:10, wis:18, cha:12,
      skills:{ Acrobatics:2, 'Animal Handling':4, Nature:4, Perception:4, Survival:4 },
      cantrips:['Shillelagh','Thorn Spray'],
      spells_1:['Entangle','Cure Wounds'],
      spells_2:[],
      features:['Spore Spray','Wild Shape'],
      equipment:['Quarterstaff','Leather Armor','Druidic Focus','Herbalism Kit'],
    },
    level5: {
      class:'Druid', subclass:'Circle of Spores',
      hp:38, ac:13, speed:30,
      str:14, dex:16, con:18, int:12, wis:20, cha:14,
      skills:{ Acrobatics:3, 'Animal Handling':7, Nature:7, Perception:7, Survival:7 },
      cantrips:['Shillelagh','Thorn Spray','Guidance','Light'],
      spells_1:['Entangle','Cure Wounds','Detect Magic','Faerie Fire'],
      spells_2:['Insect Plague','Suggestion'],
      features:['Spore Spray','Fungal Network','Wild Shape (CR 1/2)','Symbiotic Entity'],
      equipment:['Quarterstaff','Leather Armor','Druidic Focus','Herbalism Kit','Spore-Infused Pouch'],
    },
  },
  dee: {
    level1: {
      class:'Bard', subclass:'College of Eloquence',
      hp:8, ac:12, speed:30,
      str:10, dex:14, con:12, int:10, wis:12, cha:16,
      skills:{ Acrobatics:2, Deception:3, History:1, Insight:1, Intimidation:3, Performance:3, Persuasion:3 },
      cantrips:['Blade Ward','Dancing Lights'],
      spells_1:['Charm Person','Cure Wounds'],
      spells_2:[],
      features:['Bardic Inspiration (d6)','Eloquent Speech'],
      equipment:['Lute','Rapier','Leather Armor','Signet Ring'],
    },
    level5: {
      class:'Bard', subclass:'College of Eloquence',
      hp:33, ac:14, speed:30,
      str:12, dex:16, con:14, int:12, wis:14, cha:18,
      skills:{ Acrobatics:3, Deception:7, History:2, Insight:4, Intimidation:7, Performance:7, Persuasion:7 },
      cantrips:['Blade Ward','Dancing Lights','Prestidigitation','Vicious Mockery'],
      spells_1:['Charm Person','Cure Wounds','Detect Magic','Feather Fall'],
      spells_2:['Invisibility','Suggestion'],
      features:['Bardic Inspiration (d8)','Eloquent Speech','Unsettling Speech','Jack of All Trades','Song of Rest'],
      equipment:['Lute','Rapier','Leather Armor','Signet Ring'],
    },
  },
  frank: {
    level1: {
      class:'Barbarian', subclass:'Path of the Beast',
      hp:14, ac:13, speed:30,
      str:16, dex:12, con:14, int:8, wis:10, cha:8,
      skills:{ Acrobatics:1, Athletics:5, Intimidation:1, Perception:2, Survival:2 },
      cantrips:[], spells_1:[], spells_2:[],
      features:['Rage (2/day)','Unarmored Defense',"Beast's Sense"],
      equipment:['Greataxe','Leather Armor',"Hunter's Tools"],
    },
    level5: {
      class:'Barbarian', subclass:'Path of the Beast',
      hp:52, ac:15, speed:30,
      str:19, dex:14, con:16, int:8, wis:12, cha:10,
      skills:{ Acrobatics:2, Athletics:7, Intimidation:2, Perception:3, Survival:3 },
      cantrips:[], spells_1:[], spells_2:[],
      features:['Rage (3/day)','Reckless Attack','Danger Sense',"Beast's Sense",'Form of the Beast (Wolf / Bear / Eagle)','Extra Attack'],
      equipment:['Greataxe','Leather Armor','Shield',"Hunter's Tools","Beast's Tooth"],
    },
  },
};
