export const CHARS = [
  {
    id: 'aragorn', short: 'Aragorn', name: 'Aragorn, Son of Arathorn',
    cls: 'Ranger · Dúnedain Wanderer',
    tag: '"I am Aragorn, son of Arathorn. If by life or death I can save you, I will."',
    lore: 'Heir to a throne he has spent his life avoiding. Reads tracks like a book, orc-sign better than most rangers read maps. Andúril was reforged for this. He is trying very hard not to make that a whole thing.',
    hp: 44, ac: 16, speed: 30, prof: 3,
    stats: { STR:16, DEX:16, CON:14, INT:12, WIS:16, CHA:14 },
    imgKey: 'aragorn', accentColor: '#7a6a3a',
  },
  {
    id: 'legolas', short: 'Legolas', name: 'Legolas Greenleaf',
    cls: 'Ranger · Woodland Marksman',
    tag: '"A red sun rises. Blood has been spilled this night."',
    lore: 'Prince of the Woodland Realm. Counts his kills out loud, mostly to needle Gimli. Can walk on snow without sinking and has never once let anyone forget it.',
    hp: 38, ac: 17, speed: 35, prof: 3,
    stats: { STR:12, DEX:20, CON:14, INT:12, WIS:16, CHA:12 },
    imgKey: 'legolas', accentColor: '#3a6a3a',
  },
  {
    id: 'gimli', short: 'Gimli', name: 'Gimli, son of Glóin',
    cls: 'Barbarian · Path of the Berserker',
    tag: '"Certainty of death. Small chance of success. What are we waiting for?"',
    lore: 'Dwarf of the Lonely Mountain. Keeps a running tally of kills against Legolas and cheats at the count. Distrusts elves on principle, is currently losing that argument with himself.',
    hp: 58, ac: 16, speed: 25, prof: 3,
    stats: { STR:18, DEX:10, CON:18, INT:8, WIS:10, CHA:8 },
    imgKey: 'gimli', accentColor: '#8a3a1a',
  },
  {
    id: 'boromir', short: 'Boromir', name: 'Boromir of Gondor',
    cls: 'Fighter · Champion',
    tag: '"One does not simply walk into Mordor. One brings a shield wall."',
    lore: 'Captain of the White Tower, here to see Gondor saved by whatever means necessary. The Ring keeps whispering to him. He keeps telling it to wait its turn.',
    hp: 52, ac: 18, speed: 30, prof: 3,
    stats: { STR:18, DEX:12, CON:16, INT:10, WIS:12, CHA:14 },
    imgKey: 'boromir', accentColor: '#8a2a2a',
  },
  {
    id: 'merry', short: 'Merry', name: 'Meriadoc Brandybuck',
    cls: 'Rogue · Scout',
    tag: '"You are in league with... no mortal can hinder me."',
    lore: 'Everyone keeps forgetting the halflings are dangerous. That is the plan. Underestimated in every room he has ever stood in, which has worked out extremely well for him so far.',
    hp: 36, ac: 16, speed: 25, prof: 3,
    stats: { STR:10, DEX:18, CON:14, INT:12, WIS:14, CHA:12 },
    imgKey: 'merry', accentColor: '#5a7a3a',
  },
  {
    id: 'pippin', short: 'Pippin', name: 'Peregrin Took',
    cls: 'Bard · College of Valor',
    tag: '"Fool of a Took. But at least he can carry a tune."',
    lore: 'Guard of the Citadel, connoisseur of second breakfasts, professional accident-haver. Louder than the situation usually calls for. Braver than the situation usually deserves.',
    hp: 33, ac: 14, speed: 25, prof: 3,
    stats: { STR:10, DEX:14, CON:12, INT:12, WIS:10, CHA:18 },
    imgKey: 'pippin', accentColor: '#b8943a',
  },
  {
    id: 'forge-your-own', short: 'Forge Your Own', name: 'Forge Your Own', isCustom: true,
    cls: 'Your Choice',
    tag: '"Not every hero answers to a name already written."',
    lore: "Want to build a character from scratch instead of playing a member of the Fellowship? Cool — connect with the DM before the trip and we'll get you set up.",
    imgKey: 'forge', accentColor: '#5a5a5a',
  },
];

export const IDENTITY = {
  aragorn: {
    doesLabel: 'HE DOES:',
    does: 'Leads from the front, tracks anything, and fights with a blade that has a better résumé than most kings.',
    forPlayer: "The player who wants to be reluctantly in charge. You didn't ask to be the leader — you just keep being right about everything.",
  },
  legolas: {
    doesLabel: 'HE DOES:',
    does: "Drops enemies at range before they close the distance, moves like the terrain isn't there, and never misses.",
    forPlayer: 'The player who wants to be effortlessly excellent. You make hard things look easy, and you will mention that it was easy.',
  },
  gimli: {
    doesLabel: 'HE DOES:',
    does: "Charges into the thickest part of the fight, shrugs off hits that should have ended him, and swings an axe like an argument he's winning.",
    forPlayer: "The player who wants to hit things until they stop being a problem. Subtlety is someone else's job.",
  },
  boromir: {
    doesLabel: 'HE DOES:',
    does: 'Holds the line, protects the party at personal cost, and hits like a wall falling on you.',
    forPlayer: "The player who wants to be the one everyone can count on — and who's quietly wrestling with a temptation the rest of the party doesn't need to know about.",
  },
  merry: {
    doesLabel: 'HE DOES:',
    does: "Slips past enemies unseen, strikes where it counts, and gets underestimated right up until it's too late for the other guy.",
    forPlayer: "The player who wants to be quietly, devastatingly effective. Nobody's watching the halfling. That's the point.",
  },
  pippin: {
    doesLabel: 'HE DOES:',
    does: 'Inspires the party, talks his way into and out of trouble, and occasionally saves the day by accident.',
    forPlayer: "The player who wants comic relief with a spine. You're here for a good time, and somehow also the reason everyone's still alive.",
  },
};

export const PRIMARY_STAT = { aragorn:'wis', legolas:'dex', gimli:'str', boromir:'str', merry:'dex', pippin:'cha' };

export const SHEETS = {
  aragorn: {
    level1: {
      class:'Ranger', subclass:'Dúnedain Wanderer',
      hp:44, ac:16, speed:30,
      str:16, dex:16, con:14, int:12, wis:16, cha:14,
      skills:{ Athletics:6, Nature:4, Perception:6, Stealth:6, Survival:6 },
      cantrips:[],
      spells_1:["Hunter's Mark",'Cure Wounds','Speak with Animals'],
      spells_2:[],
      features:['Favored Enemy (Orcs & Uruk-hai)','Natural Explorer','Extra Attack',"Land's Stride",'Colossus Slayer'],
      equipment:['Andúril (Longsword)','Longbow','Studded Leather Armor','Elven Cloak'],
    },
    level5: {
      class:'Ranger', subclass:'Dúnedain Wanderer',
      hp:44, ac:16, speed:30,
      str:16, dex:16, con:14, int:12, wis:16, cha:14,
      skills:{ Athletics:6, Nature:4, Perception:6, Stealth:6, Survival:6 },
      cantrips:[],
      spells_1:["Hunter's Mark",'Cure Wounds','Speak with Animals'],
      spells_2:[],
      features:['Favored Enemy (Orcs & Uruk-hai)','Natural Explorer','Extra Attack',"Land's Stride",'Colossus Slayer'],
      equipment:['Andúril (Longsword)','Longbow','Studded Leather Armor','Elven Cloak'],
    },
  },
  legolas: {
    level1: {
      class:'Ranger', subclass:'Woodland Marksman',
      hp:38, ac:17, speed:35,
      str:12, dex:20, con:14, int:12, wis:16, cha:12,
      skills:{ Acrobatics:8, Perception:6, Stealth:8, Survival:6 },
      cantrips:[],
      spells_1:["Hunter's Mark",'Cure Wounds'],
      spells_2:[],
      features:['Fighting Style (Archery)','Extra Attack','Horde Breaker',"Land's Stride",'Keen Elven Senses'],
      equipment:['Elven Longbow','Twin White Knives','Elven Cloak'],
    },
    level5: {
      class:'Ranger', subclass:'Woodland Marksman',
      hp:38, ac:17, speed:35,
      str:12, dex:20, con:14, int:12, wis:16, cha:12,
      skills:{ Acrobatics:8, Perception:6, Stealth:8, Survival:6 },
      cantrips:[],
      spells_1:["Hunter's Mark",'Cure Wounds'],
      spells_2:[],
      features:['Fighting Style (Archery)','Extra Attack','Horde Breaker',"Land's Stride",'Keen Elven Senses'],
      equipment:['Elven Longbow','Twin White Knives','Elven Cloak'],
    },
  },
  gimli: {
    level1: {
      class:'Barbarian', subclass:'Path of the Berserker',
      hp:58, ac:16, speed:25,
      str:18, dex:10, con:18, int:8, wis:10, cha:8,
      skills:{ Athletics:7, Intimidation:2, Perception:3, Survival:3 },
      cantrips:[], spells_1:[], spells_2:[],
      features:['Rage (3/day)','Reckless Attack','Danger Sense','Frenzy','Extra Attack'],
      equipment:['Dwarven Battleaxe','Throwing Axes','Chainmail','Ale (unlimited supply, apparently)'],
    },
    level5: {
      class:'Barbarian', subclass:'Path of the Berserker',
      hp:58, ac:16, speed:25,
      str:18, dex:10, con:18, int:8, wis:10, cha:8,
      skills:{ Athletics:7, Intimidation:2, Perception:3, Survival:3 },
      cantrips:[], spells_1:[], spells_2:[],
      features:['Rage (3/day)','Reckless Attack','Danger Sense','Frenzy','Extra Attack'],
      equipment:['Dwarven Battleaxe','Throwing Axes','Chainmail','Ale (unlimited supply, apparently)'],
    },
  },
  boromir: {
    level1: {
      class:'Fighter', subclass:'Champion',
      hp:52, ac:18, speed:30,
      str:18, dex:12, con:16, int:10, wis:12, cha:14,
      skills:{ Athletics:7, Intimidation:5, Perception:4, Persuasion:5 },
      cantrips:[], spells_1:[], spells_2:[],
      features:['Action Surge','Extra Attack','Second Wind','Improved Critical'],
      equipment:['Longsword','Shield','Chainmail','Horn of Gondor'],
    },
    level5: {
      class:'Fighter', subclass:'Champion',
      hp:52, ac:18, speed:30,
      str:18, dex:12, con:16, int:10, wis:12, cha:14,
      skills:{ Athletics:7, Intimidation:5, Perception:4, Persuasion:5 },
      cantrips:[], spells_1:[], spells_2:[],
      features:['Action Surge','Extra Attack','Second Wind','Improved Critical'],
      equipment:['Longsword','Shield','Chainmail','Horn of Gondor'],
    },
  },
  merry: {
    level1: {
      class:'Rogue', subclass:'Scout',
      hp:36, ac:16, speed:25,
      str:10, dex:18, con:14, int:12, wis:14, cha:12,
      skills:{ Acrobatics:7, Perception:5, Stealth:7, Survival:5 },
      cantrips:[], spells_1:[], spells_2:[],
      features:['Sneak Attack (3d6)','Cunning Action','Uncanny Dodge','Halfling Luck','Brave'],
      equipment:['Barrow-blade (Shortsword)','Shortbow','Leather Armor',"Thief's Tools"],
    },
    level5: {
      class:'Rogue', subclass:'Scout',
      hp:36, ac:16, speed:25,
      str:10, dex:18, con:14, int:12, wis:14, cha:12,
      skills:{ Acrobatics:7, Perception:5, Stealth:7, Survival:5 },
      cantrips:[], spells_1:[], spells_2:[],
      features:['Sneak Attack (3d6)','Cunning Action','Uncanny Dodge','Halfling Luck','Brave'],
      equipment:['Barrow-blade (Shortsword)','Shortbow','Leather Armor',"Thief's Tools"],
    },
  },
  pippin: {
    level1: {
      class:'Bard', subclass:'College of Valor',
      hp:33, ac:14, speed:25,
      str:10, dex:14, con:12, int:12, wis:10, cha:18,
      skills:{ Deception:7, Insight:3, Performance:7, Persuasion:7 },
      cantrips:['Vicious Mockery','Dancing Lights'],
      spells_1:['Heroism','Healing Word','Charm Person'],
      spells_2:['Invisibility','Enhance Ability'],
      features:['Bardic Inspiration (d8)','Jack of All Trades','Combat Inspiration','Song of Rest'],
      equipment:['Shortsword','Lute','Leather Armor','A Second Breakfast (always)'],
    },
    level5: {
      class:'Bard', subclass:'College of Valor',
      hp:33, ac:14, speed:25,
      str:10, dex:14, con:12, int:12, wis:10, cha:18,
      skills:{ Deception:7, Insight:3, Performance:7, Persuasion:7 },
      cantrips:['Vicious Mockery','Dancing Lights'],
      spells_1:['Heroism','Healing Word','Charm Person'],
      spells_2:['Invisibility','Enhance Ability'],
      features:['Bardic Inspiration (d8)','Jack of All Trades','Combat Inspiration','Song of Rest'],
      equipment:['Shortsword','Lute','Leather Armor','A Second Breakfast (always)'],
    },
  },
};
